name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Configurer Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurer Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Décoder le keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/krenoa-release.keystore

      - name: Compiler l'APK
        run: gradle assembleDebug -PGEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} -PKEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }} -PKEY_ALIAS=${{ secrets.KEY_ALIAS }} -PKEY_PASSWORD=${{ secrets.KEY_PASSWORD }}

      - name: Sauvegarder l'APK
        uses: actions/upload-artifact@v4
        with:
          name: krenoa-apk
          path: app/build/outputs/apk/debug/app-debug.apk
