name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Configurer Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurer Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Récupérer la clé de signature depuis le cache
        uses: actions/cache@v4
        with:
          path: /home/runner/.android/debug.keystore
          key: nexora-cle-signature-v1

      - name: Créer la clé si elle n'existe pas encore
        run: |
          mkdir -p ~/.android
          if [ ! -f ~/.android/debug.keystore ]; then
            keytool -genkeypair -v -keystore ~/.android/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10950 -dname "CN=Android Debug,O=Android,C=US"
          fi

      - name: Compiler l'APK
        run: gradle assembleDebug

      - name: Sauvegarder l'APK
        uses: actions/upload-artifact@v4
        with:
          name: nexora-apk
          path: app/build/outputs/apk/debug/app-debug.apk
