name: Create Krenoa Keystore

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
      - name: Créer la clé
        run: |
          keytool -genkeypair \
          -v \
          -keystore krenoa-release.keystore \
          -alias krenoa \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -storepass Krenoa2026 \
          -keypass Krenoa2026 \
          -dname "CN=Krenoa,O=Krenoa,C=CM"

      - name: Encoder en base64
        run: base64 -w 0 krenoa-release.keystore > krenoa-base64.txt

      - name: Sauvegarder le texte encodé
        uses: actions/upload-artifact@v4
        with:
          name: krenoa-keystore-base64
          path: krenoa-base64.txt
