name: Create Nexora Keystore

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
      - name: Créer la clé
        run: |
          keytool -genkeypair \
          -v \
          -keystore nexora-release.keystore \
          -alias nexora \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -storepass Nexora2026 \
          -keypass Nexora2026 \
          -dname "CN=Nexora,O=Nexora,C=CM"

      - name: Sauvegarder la clé
        uses: actions/upload-artifact@v4
        with:
          name: nexora-keystore
          path: nexora-release.keystore
